"""Add is_direct to channels

Revision ID: 026df6d29988
Revises: d59466ea55ee
Create Date: 2026-03-19 03:02:41.776592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '026df6d29988'
down_revision: Union[str, Sequence[str], None] = 'd59466ea55ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('is_direct', sa.Boolean(), nullable=False))
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('channels', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('channels', 'is_direct')
    # ### end Alembic commands ###
